"""add products table

Revision ID: 8651c0024875
Revises: 9d54c8441b86
Create Date: 2025-03-31 19:53:23.329536

"""
from typing import Sequence, Union
from datetime import UTC

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8651c0024875'
down_revision: Union[str, None] = '9d54c8441b86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('category_id', sa.Enum('ELECTRONICS', 'CLOTHING', 'FOOD', 'BOOKS', 'OTHER', name='productcategory'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=UTC), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
