services:
  postgres:
    image: postgres:15
    container_name: internet-shop-postgres
    env_file:
      - .env
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5433"
    healthcheck:
          test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
          interval: 10s
          timeout: 5s
          retries: 5
  backend:
    build: .
    container_name: internet-shop-backend
    env_file:
      - .env
    ports:
      - "${API_PORT}:8000"
    restart: always
    depends_on:
      - postgres
    command: sh -c "alembic upgrade head && uvicorn app:app --reload --host 0.0.0.0 --port 8000"